// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inventrack.API.Models;

public partial class Almacene
{
    public int AlmacenId { get; set; }

    public string Nombre { get; set; }

    public int DireccionId { get; set; }

    public string Telefono { get; set; }

    public virtual Direccione Direccion { get; set; }

    public virtual ICollection<MovimientosPaquete> MovimientosPaquetes { get; set; } = new List<MovimientosPaquete>();

    public virtual ICollection<Paquete> Paquetes { get; set; } = new List<Paquete>();

    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();
}