// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inventrack.API.Models;

public partial class Direccione
{
    public int DireccionId { get; set; }

    public string Calle { get; set; }

    public string Ciudad { get; set; }

    public string Provincia { get; set; }

    public string CodigoPostal { get; set; }

    public string Pais { get; set; }

    public virtual ICollection<Almacene> Almacenes { get; set; } = new List<Almacene>();

    public virtual ICollection<Paquete> PaqueteDireccionDestinos { get; set; } = new List<Paquete>();

    public virtual ICollection<Paquete> PaqueteDireccionOrigens { get; set; } = new List<Paquete>();
}