// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Inventrack.API.Models;

public partial class InventrackContext : DbContext
{
    public InventrackContext(DbContextOptions<InventrackContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Almacen> Almacenes { get; set; }

    public virtual DbSet<Direccion> Direcciones { get; set; }

    public virtual DbSet<Envio> Envios { get; set; }

    public virtual DbSet<EnvioRuta> EnvioRutas { get; set; }

    public virtual DbSet<EstadosEnvio> EstadosEnvios { get; set; }

    public virtual DbSet<Incidencia> Incidencias { get; set; }

    public virtual DbSet<MovimientosPaquete> MovimientosPaquetes { get; set; }

    public virtual DbSet<Pago> Pagos { get; set; }

    public virtual DbSet<Paquete> Paquetes { get; set; }

    public virtual DbSet<Rol> Roles { get; set; }

    public virtual DbSet<Ruta> Rutas { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Almacen>(entity =>
        {
            entity.HasKey(e => e.AlmacenId).HasName("PK__Almacene__022A087610C4052E");

            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Telefono).HasMaxLength(20);

            entity.HasOne(d => d.Direccion).WithMany(p => p.Almacenes)
                .HasForeignKey(d => d.DireccionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Almacenes__Direc__7A672E12");
        });

        modelBuilder.Entity<Direccion>(entity =>
        {
            entity.HasKey(e => e.DireccionId).HasName("PK__Direccio__68906D641E1D5C73");

            entity.Property(e => e.Calle)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Ciudad)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CodigoPostal)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Pais)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Provincia)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Envio>(entity =>
        {
            entity.HasKey(e => e.EnvioId).HasName("PK__Envios__D024E23F235798CB");

            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FechaEntrega).HasColumnType("datetime");
            entity.Property(e => e.FechaSalida)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IntentosEntrega).HasDefaultValue(0);

            entity.HasOne(d => d.Paquete).WithMany(p => p.Envios)
                .HasForeignKey(d => d.PaqueteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Envios__PaqueteI__123EB7A3");

            entity.HasOne(d => d.Repartidor).WithMany(p => p.Envios)
                .HasForeignKey(d => d.RepartidorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Envios__Repartid__1332DBDC");
        });

        modelBuilder.Entity<EnvioRuta>(entity =>
        {
            entity.HasKey(e => e.EnvioRutaId).HasName("PK__EnvioRut__1F63186CC101BD46");

            entity.HasOne(d => d.Envio).WithMany(p => p.EnvioRuta)
                .HasForeignKey(d => d.EnvioId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__EnvioRuta__Envio__17F790F9");

            entity.HasOne(d => d.Ruta).WithMany(p => p.EnvioRuta)
                .HasForeignKey(d => d.RutaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__EnvioRuta__RutaI__18EBB532");
        });

        modelBuilder.Entity<EstadosEnvio>(entity =>
        {
            entity.HasKey(e => e.EstadoId).HasName("PK__EstadosE__FEF86B004B9789B7");

            entity.ToTable("EstadosEnvio");

            entity.HasIndex(e => e.Nombre, "UQ__EstadosE__75E3EFCFA562029E").IsUnique();

            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Incidencia>(entity =>
        {
            entity.HasKey(e => e.IncidenciaId).HasName("PK__Incidenc__E41133E6E75A6DC7");

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Fecha)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Resuelta).HasDefaultValue(false);

            entity.HasOne(d => d.Paquete).WithMany(p => p.Incidencia)
                .HasForeignKey(d => d.PaqueteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Incidenci__Paque__1DB06A4F");

            entity.HasOne(d => d.Usuario).WithMany(p => p.Incidencia)
                .HasForeignKey(d => d.UsuarioId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Incidenci__Usuar__1EA48E88");
        });

        modelBuilder.Entity<MovimientosPaquete>(entity =>
        {
            entity.HasKey(e => e.MovimientoId).HasName("PK__Movimien__BF923C2CE5CE1C26");

            entity.ToTable("MovimientosPaquete");

            entity.Property(e => e.FechaMovimiento)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Observaciones).HasMaxLength(255);
            entity.Property(e => e.TipoMovimiento)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Almacen).WithMany(p => p.MovimientosPaquetes)
                .HasForeignKey(d => d.AlmacenId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Movimient__Almac__0B91BA14");

            entity.HasOne(d => d.Paquete).WithMany(p => p.MovimientosPaquetes)
                .HasForeignKey(d => d.PaqueteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Movimient__Paque__0A9D95DB");

            entity.HasOne(d => d.Usuario).WithMany(p => p.MovimientosPaquetes)
                .HasForeignKey(d => d.UsuarioId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Movimient__Usuar__0C85DE4D");
        });

        modelBuilder.Entity<Pago>(entity =>
        {
            entity.HasKey(e => e.PagoId).HasName("PK__Pagos__F00B613897C07732");

            entity.Property(e => e.FechaPago)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.MetodoPago)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Monto).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Cliente).WithMany(p => p.Pagos)
                .HasForeignKey(d => d.ClienteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Pagos__ClienteId__22751F6C");

            entity.HasOne(d => d.Paquete).WithMany(p => p.Pagos)
                .HasForeignKey(d => d.PaqueteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Pagos__PaqueteId__236943A5");
        });

        modelBuilder.Entity<Paquete>(entity =>
        {
            entity.HasKey(e => e.PaqueteId).HasName("PK__Paquetes__7B9F2DB29380BA16");

            entity.HasIndex(e => e.CodigoSeguimiento, "UQ__Paquetes__6A8777541CEA1126").IsUnique();

            entity.Property(e => e.CodigoSeguimiento)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Descripcion).HasMaxLength(255);
            entity.Property(e => e.Dimensiones).HasMaxLength(100);
            entity.Property(e => e.EstadoId).HasDefaultValue(1);
            entity.Property(e => e.FechaRegistro)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Peso).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.AlmacenActual).WithMany(p => p.Paquetes)
                .HasForeignKey(d => d.AlmacenActualId)
                .HasConstraintName("FK_Paquetes_Almacenes_AlmacenActual");

            entity.HasOne(d => d.Destinatario).WithMany(p => p.Paquetes)
                .HasForeignKey(d => d.DestinatarioId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Paquetes__Client__02FC7413");

            entity.HasOne(d => d.DireccionDestino).WithMany(p => p.PaqueteDireccionDestinos)
                .HasForeignKey(d => d.DireccionDestinoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Paquetes__Direcc__04E4BC85");

            entity.HasOne(d => d.DireccionOrigen).WithMany(p => p.PaqueteDireccionOrigens)
                .HasForeignKey(d => d.DireccionOrigenId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Paquetes__Direcc__03F0984C");

            entity.HasOne(d => d.Estado).WithMany(p => p.Paquetes)
                .HasForeignKey(d => d.EstadoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Paquetes__Estado__05D8E0BE");
        });

        modelBuilder.Entity<Rol>(entity =>
        {
            entity.HasKey(e => e.RolId).HasName("PK__Roles__F92302F1CBA1DC2E");

            entity.HasIndex(e => e.Nombre, "UQ__Roles__75E3EFCFC3A1FF45").IsUnique();

            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Ruta>(entity =>
        {
            entity.HasKey(e => e.RutaId).HasName("PK__Rutas__7B61998E2B4B4C78");

            entity.Property(e => e.Descripcion).HasMaxLength(255);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.UsuarioId).HasName("PK__Usuarios__2B3DE7B8D6A34537");

            entity.HasIndex(e => e.Email, "UQ__Usuarios__A9D1053483C8B8F8").IsUnique();

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.ContrasenaHash)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.FechaRegistro)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Telefono).HasMaxLength(20);

            entity.HasOne(d => d.Almacen).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.AlmacenId)
                .HasConstraintName("FK_Usuarios_Almacenes");

            entity.HasOne(d => d.Rol).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.RolId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Usuarios__RolId__75A278F5");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}