// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inventrack.API.Models;

public partial class MovimientosPaquete
{
    public int MovimientoId { get; set; }

    public int PaqueteId { get; set; }

    public int AlmacenId { get; set; }

    public int UsuarioId { get; set; }

    public string TipoMovimiento { get; set; }

    public DateTime? FechaMovimiento { get; set; }

    public string Observaciones { get; set; }

    public virtual Almacen Almacen { get; set; }

    public virtual Paquete Paquete { get; set; }

    public virtual Usuario Usuario { get; set; }
}