// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inventrack.API.Models;

public partial class Pago
{
    public int PagoId { get; set; }

    public int ClienteId { get; set; }

    public int PaqueteId { get; set; }

    public decimal Monto { get; set; }

    public string MetodoPago { get; set; }

    public DateTime? FechaPago { get; set; }

    public virtual Usuario Cliente { get; set; }

    public virtual Paquete Paquete { get; set; }
}