// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inventrack.API.Models;

public partial class Paquete
{
    public int PaqueteId { get; set; }

    public int DestinatarioId { get; set; }

    public string CodigoSeguimiento { get; set; }

    public decimal Peso { get; set; }

    public string Dimensiones { get; set; }

    public string Descripcion { get; set; }

    public int DireccionOrigenId { get; set; }

    public int DireccionDestinoId { get; set; }

    public int EstadoId { get; set; }

    public DateTime? FechaRegistro { get; set; }

    public int? AlmacenActualId { get; set; }

    public virtual Almacen AlmacenActual { get; set; }

    public virtual Usuario Destinatario { get; set; }

    public virtual Direccion DireccionDestino { get; set; }

    public virtual Direccion DireccionOrigen { get; set; }

    public virtual ICollection<Envio> Envios { get; set; } = new List<Envio>();

    public virtual EstadosEnvio Estado { get; set; }

    public virtual ICollection<Incidencia> Incidencia { get; set; } = new List<Incidencia>();

    public virtual ICollection<MovimientosPaquete> MovimientosPaquetes { get; set; } = new List<MovimientosPaquete>();

    public virtual ICollection<Pago> Pagos { get; set; } = new List<Pago>();
}